server:
  port: 8082
  
spring:
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    config:
        import-check:
          enabled: false
  datasource:
    url: jdbc:postgresql://localhost:4545/microservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
      name: HOTEL-SERVICE

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#     defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: add here your OKTA issuer ID
    audience: api://default